<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: int322_162a02
 * Date: Fri, 12 Aug 2016 00:12:09 -0400
 */

$conf['title'] = 'INT322 Assignment2';
$conf['template'] = 'zenlike';
$conf['tagline'] = 'Web Programming using PHP';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'rss';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['plugin']['captcha']['mode'] = 'math';
$conf['plugin']['captcha']['loginprotect'] = 1;
$conf['plugin']['gallery']['thumbnail_width'] = 150;
$conf['plugin']['gallery']['thumbnail_height'] = 150;
$conf['plugin']['gallery']['image_width'] = 500;
$conf['plugin']['gallery']['image_height'] = 300;
$conf['plugin']['gallery']['cols'] = 3;
$conf['plugin']['gallery']['options'] = 'cache,lightbox,random';
$conf['plugin']['freechat']['title'] = 'Welcome to Chat Room';
$conf['plugin']['freechat']['height'] = 100;
$conf['plugin']['freechat']['frozen_nick'] = 0;
$conf['plugin']['freechat']['channels'] = 'INT322 room';
$conf['plugin']['statdisplay']['lines'] = 1000;
$conf['plugin']['overlay']['admin'] = '0';
$conf['plugin']['overlay']['register'] = '0';

// end auto-generated content
